server:
  port: 9001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Train-Component
          uri: http://localhost:8080/
          predicates:
            - Path=/train/**
        - id: Reservation-Component
          uri: http://localhost:8081/
          predicates:
            - Path=/reservation/**
        - id: User-Component
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
        - id: Payment-Component
          uri: http://localhost:8083/
          predicates:
            - Path=/payment/**

